#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debe ser root\e[00m"
	exit 1
fi

case "$1" in
	single)
		clear
		casa=$(echo $2 | tr [a-z] [A-Z])
		echo -e "\e[00;1;92m$casa\e[00m"
		echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $casa | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u -b 255.255.255.255 4000
		echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $casa | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u -b 255.255.255.255 9
		echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $casa | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u -b 255.255.255.255 7
		wakeonlan $casa
		wakeonlan -p 7 $casa
		echo -e "\e[00;1;92mFinalizado.\e[00m"
		;;

	multi)
		clear
		cat $2 | tr [a-z] [A-Z] > /tmp/mac.txt
		for f in $(cat /tmp/mac.txt | cut -c 1-17)
		do
			echo -e "\e[00;1;92m$f\e[00m"
			echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $f | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u -b 255.255.255.255 4000
			echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $f | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u -b 255.255.255.255 9
			echo -e $(echo $(printf 'f%.0s' {1..12}; printf "$(echo $f | sed 's/://g')%.0s" {1..16}) | sed -e 's/../\\x&/g') | nc -w1 -u -b 255.255.255.255 7
			wakeonlan $f
			wakeonlan -p 7 $f
		done
		echo -e "\e[00;1;92mFinalizado.\e[00m"
		;;

	*)
		echo "uso: $(basename $0) {single XX:XX:XX:XX:XX:XX|multi /ruta/al/archivo.txt}"
		;;

esac
exit 0
